### PR TITLE
Make interopt tests only publish locally

### PR DESCRIPTION
**Pull request by mdedetrich**
SBT 1.9.0-RC1 was released which contains the fix I contributed upstream at https://github.com/sbt/sbt/pull/7165 that allows `publish`/`publishLocal` to respect different settings for `skip`.

I tested this locally, i.e. `interop-tests/publish` doesn't actually publish anything where as `interop-tests/publishLocal` does publish locally

```
[IJ]interop-tests/publishLocal
[info] Wrote /Users/mdedetrich/github/incubator-pekko-grpc/interop-tests/target/scala-2.12/pekko-grpc-interop-tests_2.12-0.0.0-21-952bb33a-20230504-0906-SNAPSHOT.pom

[info] Compiling 1 protobuf files to /Users/mdedetrich/github/incubator-pekko-grpc/runtime/target/scala-2.12/src_managed/main
[info] Generating Apache Pekko gRPC service interface for grpc.reflection.v1alpha.reflection.ServerReflection
[info] Generating Apache Pekko gRPC client for grpc.reflection.v1alpha.reflection.ServerReflection
[info] Generating Apache Pekko gRPC service handler for grpc.reflection.v1alpha.reflection.ServerReflection
[info] Compiling 83 protobuf files to /Users/mdedetrich/github/incubator-pekko-grpc/interop-tests/target/scala-2.12/src_managed/main
google/api/billing.proto:19:1: warning: Import google/api/metric.proto is unused.
google/api/service.proto:34:1: warning: Import google/api/resource.proto is unused.
google/api/service.proto:27:1: warning: Import google/api/label.proto is unused.
google/api/service.proto:38:1: warning: Import google/protobuf/any.proto is unused.
[info] Generating Apache Pekko gRPC service interface for com.example.crdts.crdt_example.CrdtExample
[info] Generating Apache Pekko gRPC service interface for example.myapp.helloworld.grpc.helloworld.GreeterService
[info] Generating Apache Pekko gRPC service interface for com.google.longrunning.operations.Operations
[info] Generating Apache Pekko gRPC service interface for io.grpc.channelz.v1.channelz.Channelz
[info] Generating Apache Pekko gRPC service interface for io.grpc.health.v1.health.Health
[info] Generating Apache Pekko gRPC service interface for io.grpc.lb.v1.load_balancer.LoadBalancer
[info] Generating Apache Pekko gRPC service interface for io.grpc.lookup.v1.rls.RouteLookupService
[info] Generating Apache Pekko gRPC service interface for io.grpc.reflection.v1alpha.reflection.ServerReflection
[info] Generating Apache Pekko gRPC service interface for io.grpc.testing.integration.metrics.MetricsService
[info] Generating Apache Pekko gRPC service interface for io.grpc.testing.integration.test.TestService
[info] Generating Apache Pekko gRPC service interface for io.grpc.testing.integration.test.UnimplementedService
[info] Generating Apache Pekko gRPC service interface for io.grpc.testing.integration.test.ReconnectService
[info] Generating Apache Pekko gRPC service interface for io.grpc.testing.integration.test.LoadBalancerStatsService
[info] Generating Apache Pekko gRPC service interface for io.grpc.testing.integration.test.XdsUpdateHealthService
[info] Generating Apache Pekko gRPC service interface for io.grpc.testing.integration.test.XdsUpdateClientConfigureService
[info] Generating Apache Pekko gRPC service interface for [com.example.crdts.CrdtExample]
[info] Generating Apache Pekko gRPC service interface for [example.myapp.helloworld.grpc.GreeterService]
[info] Generating Apache Pekko gRPC service interface for [com.google.longrunning.Operations]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.channelz.v1.Channelz]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.health.v1.Health]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.lb.v1.LoadBalancer]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.lookup.v1.RouteLookupService]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.reflection.v1alpha.ServerReflection]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.testing.integration.MetricsService]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.testing.integration.TestService]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.testing.integration.UnimplementedService]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.testing.integration.ReconnectService]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.testing.integration.LoadBalancerStatsService]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.testing.integration.XdsUpdateHealthService]
[info] Generating Apache Pekko gRPC service interface for [io.grpc.testing.integration.XdsUpdateClientConfigureService]
[info] Generating Apache Pekko gRPC client for com.example.crdts.crdt_example.CrdtExample
[info] Generating Apache Pekko gRPC client for example.myapp.helloworld.grpc.helloworld.GreeterService
[info] Generating Apache Pekko gRPC client for com.google.longrunning.operations.Operations
[info] Generating Apache Pekko gRPC client for io.grpc.channelz.v1.channelz.Channelz
[info] Generating Apache Pekko gRPC client for io.grpc.health.v1.health.Health
[info] Generating Apache Pekko gRPC client for io.grpc.lb.v1.load_balancer.LoadBalancer
[info] Generating Apache Pekko gRPC client for io.grpc.lookup.v1.rls.RouteLookupService
[info] Generating Apache Pekko gRPC client for io.grpc.reflection.v1alpha.reflection.ServerReflection
[info] Generating Apache Pekko gRPC client for io.grpc.testing.integration.metrics.MetricsService
[info] Generating Apache Pekko gRPC client for io.grpc.testing.integration.test.TestService
[info] Generating Apache Pekko gRPC client for io.grpc.testing.integration.test.UnimplementedService
[info] Generating Apache Pekko gRPC client for io.grpc.testing.integration.test.ReconnectService
[info] Generating Apache Pekko gRPC client for io.grpc.testing.integration.test.LoadBalancerStatsService
[info] Generating Apache Pekko gRPC client for io.grpc.testing.integration.test.XdsUpdateHealthService
[info] Generating Apache Pekko gRPC client for io.grpc.testing.integration.test.XdsUpdateClientConfigureService
[info] Generating Apache Pekko gRPC Client [com.example.crdts.CrdtExample]
[info] Generating Apache Pekko gRPC Lifted Client interface[com.example.crdts.CrdtExample]
[info] Generating Apache Pekko gRPC Client [example.myapp.helloworld.grpc.GreeterService]
[info] Generating Apache Pekko gRPC Lifted Client interface[example.myapp.helloworld.grpc.GreeterService]
[info] Generating Apache Pekko gRPC Client [com.google.longrunning.Operations]
[info] Generating Apache Pekko gRPC Lifted Client interface[com.google.longrunning.Operations]
[info] Generating Apache Pekko gRPC Client [io.grpc.channelz.v1.Channelz]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.channelz.v1.Channelz]
[info] Generating Apache Pekko gRPC Client [io.grpc.health.v1.Health]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.health.v1.Health]
[info] Generating Apache Pekko gRPC Client [io.grpc.lb.v1.LoadBalancer]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.lb.v1.LoadBalancer]
[info] Generating Apache Pekko gRPC Client [io.grpc.lookup.v1.RouteLookupService]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.lookup.v1.RouteLookupService]
[info] Generating Apache Pekko gRPC Client [io.grpc.reflection.v1alpha.ServerReflection]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.reflection.v1alpha.ServerReflection]
[info] Generating Apache Pekko gRPC Client [io.grpc.testing.integration.MetricsService]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.testing.integration.MetricsService]
[info] Generating Apache Pekko gRPC Client [io.grpc.testing.integration.TestService]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.testing.integration.TestService]
[info] Generating Apache Pekko gRPC Client [io.grpc.testing.integration.UnimplementedService]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.testing.integration.UnimplementedService]
[info] Generating Apache Pekko gRPC Client [io.grpc.testing.integration.ReconnectService]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.testing.integration.ReconnectService]
[info] Generating Apache Pekko gRPC Client [io.grpc.testing.integration.LoadBalancerStatsService]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.testing.integration.LoadBalancerStatsService]
[info] Generating Apache Pekko gRPC Client [io.grpc.testing.integration.XdsUpdateHealthService]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.testing.integration.XdsUpdateHealthService]
[info] Generating Apache Pekko gRPC Client [io.grpc.testing.integration.XdsUpdateClientConfigureService]
[info] Generating Apache Pekko gRPC Lifted Client interface[io.grpc.testing.integration.XdsUpdateClientConfigureService]
[info] Generating Apache Pekko gRPC service handler for com.example.crdts.crdt_example.CrdtExample
[info] Generating Apache Pekko gRPC service power API handler for com.example.crdts.crdt_example.CrdtExample
[info] Generating Apache Pekko gRPC service power API interface for com.example.crdts.crdt_example.CrdtExample
[info] Generating Apache Pekko gRPC service handler for example.myapp.helloworld.grpc.helloworld.GreeterService
[info] Generating Apache Pekko gRPC service power API handler for example.myapp.helloworld.grpc.helloworld.GreeterService
[info] Generating Apache Pekko gRPC service power API interface for example.myapp.helloworld.grpc.helloworld.GreeterService
[info] Generating Apache Pekko gRPC service handler for com.google.longrunning.operations.Operations
[info] Generating Apache Pekko gRPC service power API handler for com.google.longrunning.operations.Operations
[info] Generating Apache Pekko gRPC service power API interface for com.google.longrunning.operations.Operations
[info] Generating Apache Pekko gRPC service handler for io.grpc.channelz.v1.channelz.Channelz
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.channelz.v1.channelz.Channelz
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.channelz.v1.channelz.Channelz
[info] Generating Apache Pekko gRPC service handler for io.grpc.health.v1.health.Health
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.health.v1.health.Health
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.health.v1.health.Health
[info] Generating Apache Pekko gRPC service handler for io.grpc.lb.v1.load_balancer.LoadBalancer
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.lb.v1.load_balancer.LoadBalancer
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.lb.v1.load_balancer.LoadBalancer
[info] Generating Apache Pekko gRPC service handler for io.grpc.lookup.v1.rls.RouteLookupService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.lookup.v1.rls.RouteLookupService
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.lookup.v1.rls.RouteLookupService
[info] Generating Apache Pekko gRPC service handler for io.grpc.reflection.v1alpha.reflection.ServerReflection
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.reflection.v1alpha.reflection.ServerReflection
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.reflection.v1alpha.reflection.ServerReflection
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.metrics.MetricsService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.metrics.MetricsService
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.testing.integration.metrics.MetricsService
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.test.TestService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.test.TestService
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.testing.integration.test.TestService
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.test.UnimplementedService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.test.UnimplementedService
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.testing.integration.test.UnimplementedService
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.test.ReconnectService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.test.ReconnectService
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.testing.integration.test.ReconnectService
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.test.LoadBalancerStatsService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.test.LoadBalancerStatsService
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.testing.integration.test.LoadBalancerStatsService
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.test.XdsUpdateHealthService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.test.XdsUpdateHealthService
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.testing.integration.test.XdsUpdateHealthService
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.test.XdsUpdateClientConfigureService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.test.XdsUpdateClientConfigureService
[info] Generating Apache Pekko gRPC service power API interface for io.grpc.testing.integration.test.XdsUpdateClientConfigureService
[info] Generating Apache Pekko gRPC service handler for com.example.crdts.CrdtExample
[info] Generating Apache Pekko gRPC service power API handler for com.example.crdts.CrdtExample
[info] Generating Apache Pekko gRPC service power interface for [com.example.crdts.CrdtExample]
[info] Generating Apache Pekko gRPC service handler for example.myapp.helloworld.grpc.GreeterService
[info] Generating Apache Pekko gRPC service power API handler for example.myapp.helloworld.grpc.GreeterService
[info] Generating Apache Pekko gRPC service power interface for [example.myapp.helloworld.grpc.GreeterService]
[info] Generating Apache Pekko gRPC service handler for com.google.longrunning.Operations
[info] Generating Apache Pekko gRPC service power API handler for com.google.longrunning.Operations
[info] Generating Apache Pekko gRPC service power interface for [com.google.longrunning.Operations]
[info] Generating Apache Pekko gRPC service handler for io.grpc.channelz.v1.Channelz
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.channelz.v1.Channelz
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.channelz.v1.Channelz]
[info] Generating Apache Pekko gRPC service handler for io.grpc.health.v1.Health
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.health.v1.Health
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.health.v1.Health]
[info] Generating Apache Pekko gRPC service handler for io.grpc.lb.v1.LoadBalancer
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.lb.v1.LoadBalancer
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.lb.v1.LoadBalancer]
[info] Generating Apache Pekko gRPC service handler for io.grpc.lookup.v1.RouteLookupService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.lookup.v1.RouteLookupService
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.lookup.v1.RouteLookupService]
[info] Generating Apache Pekko gRPC service handler for io.grpc.reflection.v1alpha.ServerReflection
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.reflection.v1alpha.ServerReflection
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.reflection.v1alpha.ServerReflection]
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.MetricsService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.MetricsService
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.testing.integration.MetricsService]
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.TestService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.TestService
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.testing.integration.TestService]
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.UnimplementedService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.UnimplementedService
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.testing.integration.UnimplementedService]
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.ReconnectService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.ReconnectService
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.testing.integration.ReconnectService]
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.LoadBalancerStatsService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.LoadBalancerStatsService
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.testing.integration.LoadBalancerStatsService]
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.XdsUpdateHealthService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.XdsUpdateHealthService
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.testing.integration.XdsUpdateHealthService]
[info] Generating Apache Pekko gRPC service handler for io.grpc.testing.integration.XdsUpdateClientConfigureService
[info] Generating Apache Pekko gRPC service power API handler for io.grpc.testing.integration.XdsUpdateClientConfigureService
[info] Generating Apache Pekko gRPC service power interface for [io.grpc.testing.integration.XdsUpdateClientConfigureService]
[warn] multiple main classes detected: run 'show discoveredMainClasses' to see the list
[info] :: delivering :: org.apache.pekko#pekko-grpc-interop-tests_2.12;0.0.0-21-952bb33a-20230504-0906-SNAPSHOT :: 0.0.0-21-952bb33a-20230504-0906-SNAPSHOT :: integration :: Thu May 04 09:08:42 CEST 2023
[info] 	delivering ivy file to /Users/mdedetrich/github/incubator-pekko-grpc/interop-tests/target/scala-2.12/ivy-0.0.0-21-952bb33a-20230504-0906-SNAPSHOT.xml
[info] 	published pekko-grpc-interop-tests_2.12 to /Users/mdedetrich/.ivy2/local/org.apache.pekko/pekko-grpc-interop-tests_2.12/0.0.0-21-952bb33a-20230504-0906-SNAPSHOT/poms/pekko-grpc-interop-tests_2.12.pom
[info] 	published pekko-grpc-interop-tests_2.12 to /Users/mdedetrich/.ivy2/local/org.apache.pekko/pekko-grpc-interop-tests_2.12/0.0.0-21-952bb33a-20230504-0906-SNAPSHOT/jars/pekko-grpc-interop-tests_2.12.jar
[info] 	published pekko-grpc-interop-tests_2.12 to /Users/mdedetrich/.ivy2/local/org.apache.pekko/pekko-grpc-interop-tests_2.12/0.0.0-21-952bb33a-20230504-0906-SNAPSHOT/srcs/pekko-grpc-interop-tests_2.12-sources.jar
[info] 	published pekko-grpc-interop-tests_2.12 to /Users/mdedetrich/.ivy2/local/org.apache.pekko/pekko-grpc-interop-tests_2.12/0.0.0-21-952bb33a-20230504-0906-SNAPSHOT/docs/pekko-grpc-interop-tests_2.12-javadoc.jar
[info] 	published ivy to /Users/mdedetrich/.ivy2/local/org.apache.pekko/pekko-grpc-interop-tests_2.12/0.0.0-21-952bb33a-20230504-0906-SNAPSHOT/ivys/ivy.xml
[success] Total time: 8 s, completed 4 May 2023, 09:08:42
```

### CODE REVIEW

**Comment by mdedetrich** [comment]
Currently blocked by https://github.com/sbt/sbt/issues/7233

**Comment by mdedetrich** [comment]
Updated PR to latest SBT 1.9.0-RC2 which fixed the previous problem however just found a new one, posted issue upstream at https://github.com/sbt/sbt/issues/7243.

**Comment by mdedetrich** [comment]
Blocked by https://github.com/apache/incubator-pekko-grpc/pull/66

**Comment by mdedetrich** [comment]
@pjfanning @nvollmar @He-Pin PR is ready now

**Review by pjfanning — APPROVED** [review]
lgtm

**Pull request merged**
