### PR TITLE
upgrade pekko and build tool versions

### PR DESCRIPTION
**Pull request by pjfanning**
* pekko 1.0.2

### CODE REVIEW

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by He-Pin** [comment]
java.lang.IllegalStateException: You are using version 1.0.2 of Apache Pekko, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 1.0.2 of the [pekko-stream-testkit, pekko-testkit] artifacts to your project. Here's a complete collection of detected artifacts: (1.0.1, [pekko-stream-testkit, pekko-testkit]), (1.0.2, [pekko-actor, pekko-discovery, pekko-protobuf-v3, pekko-stream]). See also:

**Review by He-Pin — CHANGES_REQUESTED** [review]
Add a group of explict deps to make sure all pekko version keeps in sync

**Comment by pjfanning** [comment]
> gradle tests is down
> 
> ```
>     java.lang.IllegalStateException: You are using version 1.0.2 of Apache Pekko, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 1.0.2 of the [pekko-stream-testkit, pekko-testkit] artifacts to your project. Here's a complete collection of detected artifacts: (1.0.1, [pekko-stream-testkit, pekko-testkit]), (1.0.2, [pekko-actor, pekko-discovery, pekko-protobuf-v3, pekko-stream]). See also: 
> ```

thanks - I'll have a look at the Gradle tests to see why this is happening (but maybe not tonight)

**Comment by He-Pin** [comment]
https://plugins.jetbrains.com/plugin/22427-sbt-dependency-analyzer
This plugin from @jxnu-liguobin can help

**Comment by pjfanning** [comment]
@He-Pin test issue fixed - the 1.0.1 version appears in a few places

**Review by He-Pin — APPROVED** [review]
Lgtm

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
