### PR TITLE
Use setup-coursier Instead downloading on every run in link-validator

### PR DESCRIPTION
**Pull request by mdedetrich**
Equivalent of https://github.com/apache/incubator-pekko/pull/367

### CODE REVIEW

**Review by nvollmar — APPROVED** [review]
lgtm

**Review by pjfanning — APPROVED** [review]
Lgtm

**Comment by mdedetrich** [comment]
Lets not merge this until https://issues.apache.org/jira/browse/INFRA-24664 is resolved

**Comment by pjfanning** [comment]
@mdedetrich I hadn't noticed this PR. I went and got https://github.com/apache/incubator-pekko-grpc/pull/94 merged.

**Pull request closed without merging**
