### PR TITLE
make sure trailers are present in StatusRuntimeException

### PR DESCRIPTION
**Pull request by jtjeferreira**
When using the pekko-http backend and a `StatusRuntimeException` is returned it lacks metadata. 

This PR fixes the case for both headers and trailers

The issue was initially reported in https://github.com/akka/akka-grpc/issues/1814 and I fixed it myself in akka-grpc

### CODE REVIEW

**Review by pjfanning — APPROVED** [review]
thanks - lgtm

**Comment by pjfanning** [comment]
@jtjeferreira there is a scalafmt issue in PekkoHttpClientUtils.scala - would you be able to fix that?

**Review by jxnu-liguobin — APPROVED** [review]

**Comment by jtjeferreira** [comment]
> @jtjeferreira there is a scalafmt issue in PekkoHttpClientUtils.scala - would you be able to fix that?

done

**Review by Roiocam — APPROVED** [review]
LGTM, Thanks

**Pull request merged**
