### PR TITLE
use latest pekko snapshots

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
lgtm

**Review by mdedetrich — CHANGES_REQUESTED** [review]
We have to ping ch.megard to bump pekko-http-cors, and he has to do it under a new version that is not `0.0.0` because he overwrites the snapshot.

Maybe this is an opportunity to ask him what we mentioned on the mailing list?

**Comment by pjfanning** [comment]
> We have to ping ch.megard to bump pekko-http-cors, and he has to do it under a new version that is not `0.0.0` because he overwrites the snapshot.
> 
> Maybe this is an opportunity to ask him what we mentioned on the mailing list?

sure, ask him if he'll grant us the code

but it would be useful to still get him to publish a new snapshot

**Comment by mdedetrich** [comment]
Ill ask him now

**Pull request closed without merging**
