### PR TITLE
remove compatibility test

### PR DESCRIPTION
**Pull request by pjfanning**
this test blocks #222 and it isn't a core feature

#228 is about writing a new test to replace this

### CODE REVIEW

**Comment by raboof** [comment]
Looking at https://github.com/protocolbuffers/protobuf-javascript/issues/127#issuecomment-1542288860 are we sure it's impossible to make this work with newer versions of protobuf?

**Comment by pjfanning** [comment]
@raboof to flip the question - is it worth blocking the upgrade of the grpc and protobuf libs until someone works out how to fix this test? https://github.com/apache/incubator-pekko-grpc/issues/228 is there to remind us that we need to add this or an equivalent test back.

**Comment by raboof** [comment]
> #228 is there to remind us that we need to add this or an equivalent test back.

TBH I'm not optimistic that that would actually happen when there's no pressing need anymore ;)

> @raboof to flip the question - is it worth blocking the upgrade of the grpc and protobuf libs until someone works out how to fix this test? 

It seems we are fairly close... let's give it a week?

**Comment by raboof** [comment]
superseded by #222

**Pull request closed without merging**
